# Generated by Django 3.0.9 on 2022-02-06 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_auto_20220130_1207'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPost',
        ),
    ]
