# Generated by Django 3.0.9 on 2022-02-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_delete_userpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_target_id', models.IntegerField()),
                ('from_user_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FriendStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('friend_id', models.IntegerField()),
            ],
        ),
    ]
