# Generated by Django 3.0.9 on 2022-02-06 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_friendrequest_friendstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='from_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='user_target_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
